language: perl
sudo: false
perl:
 - "v5.10"
 - "v5.10.1"
 - "v5.12.4"
 - "v5.14"
 - "v5.16.2"
 - "v5.18"
 - "v5.20.2"
 - "v5.22"
 - "dev"
matrix:
  include:
    - perl: 5.22
      env: COVERAGE=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto