language: perl
sudo: false
perl:
 - "5.10"
 - "5.10.1"
 - "5.12.4"
 - "5.14"
 - "5.16.2"
 - "5.18"
 - "5.20.2"
 - "5.22"
 - "dev"
matrix:
  include:
    - perl: 5.22
      env: COVERAGE=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto